import React from "react";

export const createInitialFormData = ({
    userData,
    editData,
    rackType,
}) => {

    if (editData) {
        return {
            ...editData,
            region: userData?.region,
        };
    }

    return {
        // General default empty form for new entries
        slNo: "",
        region: userData?.region,
        circle: userData?.circle,
        siteName: userData?.site,
        equipmentLocation: "",
        equipmentRackNo: "",
        rackName: "",
        rfaiNo: "",
        rackPowerOnDate: "",
        rackType: rackType[0],
        powerType: "",
        rackSize: "",
        rackHeight: editData?.rackDimensions?.height || "",
        rackWidth: editData?.rackDimensions?.width || "",
        rackDepth: editData?.rackDimensions?.depth || "",
        frontTopTemp: "",
        frontMiddleTemp: "",
        frontBottomTemp: "",
        backTopTemp: "",
        backMiddleTemp: "",
        backBottomTemp: "",
        rackDescription: "",
        totalRackUSpace: "",
        usedRackUSpace: "",
        freeRackUSpace: "",
        rackDomainType: "",
        rackOwnerName: "",
        drTestStatus: "",
        drTestDate: "",

        // Source A
        smpsRatingA: "",
        smpsNameA: "",
        dbNumberA: "",
        incomerRatingA: "",
        cableSizeA: "",
        cableLengthA: "",
        cableRunA: "",
        equipmentRackNoA: "",
        rackNameA: "",
        rackIncomingCableSizeA: "",
        rackCableLengthA: "",
        rackCableRunA: "",
        rackCableTaggingA: "",
        dbMcbNumberA: "",
        dbVoltageA: "",
        dbMcbRatingA: "",
        tempOnMcbA: "",
        dbMcbLabelA: "",
        runningLoadA: "",
        cableCapacityA: "",
        pctLoadCableA: "",
        pctLoadMcbA: "",
        rackEndNoDbA: "",
        rackEndDcdbNameA: "",
        rackEndVoltageA: "",
        rackEndRunningLoadA: "",
        rackEndMcbRatingA: "",
        rackEndPctLoadMcbA: "",

        // Source B
        smpsRatingB: "",
        smpsNameB: "",
        dbNumberB: "",
        incomerRatingB: "",
        cableSizeB: "",
        cableLengthB: "",
        cableRunB: "",
        equipmentRackNoB: "",
        rackNameB: "",
        rackIncomingCableSizeB: "",
        rackCableLengthB: "",
        rackCableRunB: "",
        rackCableTaggingB: "",
        dbMcbNumberB: "",
        dbVoltageB: "",
        dbMcbRatingB: "",
        tempOnMcbB: "",
        dbMcbLabelB: "",
        runningLoadB: "",
        cableCapacityB: "",
        pctLoadCableB: "",
        pctLoadMcbB: "",
        rackEndNoDbB: "",
        rackEndDcdbNameB: "",
        rackEndVoltageB: "",
        rackEndRunningLoadB: "",
        rackEndMcbRatingB: "",
        rackEndPctLoadMcbB: "",

        // Capacity Gap Analysis
        totalLoadBoth: "",
        bothCableCapacity: "",
        bothPctLoadCable: "",
        bothPctLoadMcb: "",
        isBothMcbSame: "",
        pctRackOccupied: "",
        remarksA: "",
        remarksB: "",
        sourceType: "",
      };
};

