import { APPROVAL_LEVELS } from "./approvalLevels";
import { getMopMaster } from "./mopMaster";

// activityMaster.js
export const getApproversFromLevels = (levels = []) => {
  return levels.flatMap(level =>
    (APPROVAL_LEVELS[level] || []).map(approver => ({
      level,
      approver
    }))
  );
};

export const getMopByActivity = (row, userData, siteConfig) => {
  const MOP_MASTER = getMopMaster(userData, row, siteConfig);
  return MOP_MASTER[row.activityDetails] || null;
};

export const ACTIVITY_MASTER = {
  UPS: [
    {
      activityDescription: "UPS EOL replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 0,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Night"
    },
    {
      activityDescription: "UPS Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 8,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "UPS Preventive maintenance (In House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 409,
      mopRequired: true,

      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fault / Alarm / Break Down - UPS",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "RED",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Flexible"
    }
  ],

  "UPS BB": [
    {
      activityDescription: "UPS BB EOL Replacement/Upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "BLUE",
      activityType: "Replacement/Upgradation",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "UPS BB Preventive Maintenance(In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive Maintenance",
      avgMonthlyCount: 127,
      mopRequired: true,

      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "UPS BB Preventive Maintenance(OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive Maintenance",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "UPS BB Cell Replacement",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/Upgradation",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "UPS BB IR Test Activity (In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "IR Testing",
      avgMonthlyCount: 127,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
  ],

  SMPS: [
    {
      activityDescription: "SMPS EOL replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 99,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Night"
    },
    {
      activityDescription: "SMPS Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "SMPS Preventive maintenance (In House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 346,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fault / Alarm / Break Down - SMPS",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "RED",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 189,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Night"
    },
    {
      activityDescription: "Battery Bank Online Discharge Test(In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 56,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Night"
    },
  ],

  "SMPS BB": [
    {
      activityDescription: "SMPS BB EOL Replacement/Upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "BLUE",
      activityType: "Replacement/Upgradation",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "SMPS BB Preventive Maintenance(In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive Maintenance",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "SMPS BB Preventive Maintenance(OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive Maintenance",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "SMPS BB Cell Replacement",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/Upgradation",
      avgMonthlyCount: 127,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Night"
    },
    {
      activityDescription: "Battery Bank Discharge test C-10(In-House)",
      performBy: "In-House",
      activityCategory: "Critical",
      activityCode: "AMBER",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 56,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Night"
    },

    {
      activityDescription: "SMPS BB IR Test Activity (In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "IR Testing",
      avgMonthlyCount: 127,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
  ],

  "Diesel Generator": [
    {
      activityDescription: "DG Set Replacement activity",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 42,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Day"
    },
    {
      activityDescription: "DG Set Preventive maintenance(OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 16,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "DG Set Preventive maintenance(In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 16,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "DG Set Radiator & Fuel tank cleaning activity",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "AMBER",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 63,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Daily DG test run",
      performBy: "In-House",
      activityCategory: "Critical",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 0,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  "Air Conditioner": [
    {
      activityDescription: "PAC EOL replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 92,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "PAC Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 15,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "PAC Preventive maintenance (In House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 108,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "PAC Compressor replacement",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 212,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "PAC ODU replacement",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 0,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    }
  ],

  "Comfort AC": [
    {
      activityDescription: "SRC/Comfort AC EOL replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 92,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "SRC/Comfort AC Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 15,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "SRC/Comfort AC Preventive maintenance (In House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 108,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "SRC/Comfort AC Compressor replacement",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 212,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "SRC/Comfort AC ODU replacement",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 0,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    }
  ],

  "HT Panel": [
    {
      activityDescription: "HT panel replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 24,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Day"
    },
    {
      activityDescription: "HT panel Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "HT panel Preventive maintenance (In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fault / Alarm / Break Down - HT Panel",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "AMBER",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 324,
      mopRequired: true,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    }

  ],

  "LT Panel": [
    {
      activityDescription: "LT panel replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 124,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Day"
    },
    {
      activityDescription: "LT panel Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "LT panel Preventive maintenance (In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fault / Alarm / Break Down - HT Panel",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "AMBER",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 324,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    }
  ],

"Solar system": [
    {
      activityDescription: "Solar system replacement/upgradation",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 124,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Day"
    },
    {
      activityDescription: "Solar system Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Solar system Preventive maintenance (In-House)",
      performBy: "In-House",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fault / Alarm / Break Down - Solar system",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "AMBER",
      activityType: "Corrective maintenance",
      avgMonthlyCount: 324,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    }
  ],

  Transformer: [
    {
      activityDescription: "Transformer Replacement(OEM)",
      performBy: "OEM",
      activityCategory: "Super Critical",
      activityCode: "RED",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 12,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "NLT",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5", "Level-6", "Level-7"],
      information: "Mr. Deepak Sanghi",
      activityTime: "Day"
    },
    {
      activityDescription: "Transformer Preventive maintenance Oil filtration",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "AMBER",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 63,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4"],
      information: "",
      activityTime: "Day"
    },
{
      activityDescription: "Transformer Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Critical",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 27,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Transformer Preventive maintenance (In-House)",
      performBy: "In-House",
      activityCategory: "Critical",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 27,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
  ],

  CCTV: [
    {
      activityDescription: "CCTV Preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  BMS: [
    {
      activityDescription: "BMS Preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],
  PFE: [
    {
      activityDescription: "Portable fire extinguisher preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  PAS: [
    {
      activityDescription: "Public address system preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  "Earth Pit": [
    {
      activityDescription: "Earth Pit Preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  "Exhaust Fan": [
    {
      activityDescription: "Exhaust Fan Preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  "Inverter": [
    {
      activityDescription: "Inverter Preventive maintenance (In-House) ",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  ACS: [
    {
      activityDescription: "Access Control System Preventive maintenance (In-House)",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Access Control System Preventive maintenance (OEM)",
      performBy: "OEM",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fault / Alarm / Break Down - Access Control System",
      performBy: "OEM",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ],

  FAS: [
    {
      activityDescription: "Fire Panel Preventive maintenance(In-House)",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fire Panel Preventive maintenance(OEM)",
      performBy: "OEM",
      activityCategory: "Minor",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Fire Panel maintenance OEM",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 24,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
  ],

  FSS: [
    {
      activityDescription: "FSS Preventive maintenance(In-House)",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "FSS Preventive maintenance(OEM)",
      performBy: "OEM",
      activityCategory: "Minor",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 32,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "FSS maintenance OEM",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 24,
      mopRequired: true,

      crRequired: true,
      crDaysBefore: 2,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
  ],

  Others: [

    {
      activityDescription: "New Rack power tapping",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Replacement/upgradation",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: true,
      crDaysBefore: 0,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Checking Power Dual Redundancy Of Racks",
      performBy: "OEM",
      activityCategory: "Major",
      activityCode: "BLUE",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 23,
      mopRequired: true,
      crRequired: true,
      crDaysBefore: 5,
      approvalLevel: "CIRCLE",
      approvalLevels: ["Initiator", "Level-1", "Level-2", "Level-3", "Level-4", "Level-5"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "MSC Floor cleaning activity",
      performBy: "In-House",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 0,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    },
    {
      activityDescription: "Pest Control activity",
      performBy: "OEM",
      activityCategory: "Minor",
      activityCode: "GREEN",
      activityType: "Preventive maintenance",
      avgMonthlyCount: 0,
      mopRequired: false,
      crRequired: false,
      crDaysBefore: 1,
      approvalLevel: "Circle",
      approvalLevels: ["Initiator", "Level-1", "Level-2"],
      information: "",
      activityTime: "Day"
    }
  ]
};
