const fields = [
  "Transformer Rating in KVA","EB SANCTION LOAD KVA","SITE LOAD (MD) in KVA","RUNNING P.F",
  "EB1 READING OPENIN","EB1 READING CLOSING","EB2 READING OPENIN","EB2 READING CLOSING",
  "EB3 READING OPENIN","EB3 READING CLOSING","EB4 READING OPENIN","EB4 READING ClOSING",
  "EB5 READING OPENIN","EB5 READING ClOSING","EB6 READING OPENIN","EB6 READING ClOSING",
  "EB7 READING OPENIN","EB7 READING ClOSING","EB8 READING OPENIN","EB8 READING ClOSING",
  "EB9 READING OPENIN","EB9 READING ClOSING","EB10 READING OPENIN","EB10 READING ClOSING",
  "EB11 READING OPENIN","EB11 READING ClOSING","TOTAL UNIT CONSUMPED","EB Capacity utilization (%)",
  "Facility Consumed Units","UPGRADATION REQUIRED","Power Failure Hrs/Mins","Office load KW",
  "Cooling Load KW","IT Load KW","Total Facility Load KW","PUE",
  "DG Working status","DG Battery status","DG - Installed Capacity in KVA","DG Utilization in KVA",
  "DG Capacity Utilization (%)","DG UP GRADATION REQUIRED","DG 1 Run HRS -Opening Reading","DG 1 Run HRS -Closing Reading",
  "DG 2 Run HRS -Opening Reading","DG 2 Run HRS -Closing Reading","DG 3 Run HRS -Opening Reading","DG 3 Run HRS -Closing Reading",
  "DG 4 Run HRS -Opening Reading","DG 4 Run HRS -Closing Reading","TOTAL DG RUN HRS","Total Diesel Consumption (L)",
  "DIESEL CPH / Hrs","Diesel Tank Capacity (L)","Diesel Available in Tank (L)","Diesel Available in Tank (%)",
  "DG1 KWH OPENING READING","DG1 KWH CLOSING READING","DG2 KWH OPENING READING","DG2 KWH CLOSING READING",
  "DG3 KWH OPENING READING","DG3 KWH CLOSING READING","DG4 KWH OPENING READING","DG4 KWH CLOSING READING",
  "TOTAL KWH CONSUPED","TOTAL DG KWH UNIT CONSUMPED","SOLAR","KWH OPENING READING","KWH CLOSING READING",
  "TOTAL KWH GENERATED","UPS","Avg UPS load (%)","UPS LOAD FOR SYSTEM IN KW","Status of Batteries",
  "Status of all UPS","INSTALLED SMPS","RUNNING DC LOAD AMP.","RUUNNING DC LOAD IN KW","INSTALLED BB AH",
  "SMPS UPGRADATIONS REQURIED","HVAC - High Side","Status AHU / Split / PAC / Floor Mount / Window / Cassete",
  "Average Room Temperature (Deg Cel)","OBSERVATIONS","Breakdown Minor","Breakdown Major","Incidents",
  "Any activity to be carried Out to Improve the Performance","FAS & FIRE SUPRESSON SYSTEMS","Status of FAS",
  "VESDA","Status of Fire Suppression system","Fire Extinguisher","CCTV SYSTEMS","No. of camera installed",
  "No. of camera in working condition","DVR / NVR Storage capacity TB","ACCESS CONTROL & BMS SYSTEMS",
  "No. of Access Reader installed","No. of Access Reader in working condition","BMS available","BMS in working condition"
];